// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/RP-f405-board/connectors/rp_f405_connector.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char* getBoardSpecificPinName(brain_pin_e brainPin) {
	switch (brainPin) {
		case Gpio::A15:
			return "PA15 Overboost Valve OBV (OEM pin 16)";
		case Gpio::B0:
			return "PB0 Idle Solenoid IAC (OEM pin 34)";
		case Gpio::B1:
			return "PB1 Aux PWM (OEM pin 27)";
		case Gpio::B10:
			return "PB10 Injector 1 (OEM pin 35)";
		case Gpio::B11:
			return "PB11 Injector 2 (OEM pin 32)";
		case Gpio::B12:
			return "PB12 Injector 4 (OEM pin 18)";
		case Gpio::B13:
			return "PB13 VSS";
		case Gpio::B14:
			return "PB14 ABS Input (OEM pin 14)";
		case Gpio::B15:
			return "PB15 Injector 3 (OEM pin 33)";
		case Gpio::B2:
			return "PB2 AC Request (OEM pin 21)";
		case Gpio::B3:
			return "PB3 EVAP Purge (OEM pin 7)";
		case Gpio::B4:
			return "PB4 Aux Switch 1 (OEM pin 8)";
		case Gpio::B5:
			return "PB5 MIL Warning Lamp (OEM pin 12)";
		case Gpio::C1:
			return "PC1 Ignition 1 (OEM pin 25)";
		case Gpio::C13:
			return "PC13 Fuel Pump Relay (OEM pin 28)";
		case Gpio::C2:
			return "PC2 Ignition 2 (OEM pin 26)";
		case Gpio::C3:
			return "PC3 Ignition 3";
		case Gpio::C4:
			return "PC4 Ignition 4";
		case Gpio::C5:
			return "PC5 Aux Switch 2 (OEM pin 13)";
		case Gpio::C6:
			return "PC6 Crank Sensor (OEM pin 4)";
		case Gpio::C7:
			return "PC7 Cam Sensor (OEM pin 23)";
		default:
			return nullptr;
	}
	return nullptr;
}
