// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/RP-f405-board/connectors/rp_f405_connector.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::B10, // PB10 Injector 1 (OEM pin 35)
	Gpio::B11, // PB11 Injector 2 (OEM pin 32)
	Gpio::B15, // PB15 Injector 3 (OEM pin 33)
	Gpio::B12, // PB12 Injector 4 (OEM pin 18)
	Gpio::B0, // PB0 Idle Solenoid IAC (OEM pin 34)
	Gpio::B1, // PB1 Aux PWM (OEM pin 27)
	Gpio::B3, // PB3 EVAP Purge (OEM pin 7)
	Gpio::A15, // PA15 Overboost Valve OBV (OEM pin 16)
	Gpio::B5, // PB5 MIL Warning Lamp (OEM pin 12)
	Gpio::C13, // PC13 Fuel Pump Relay (OEM pin 28)
	Gpio::C1, // PC1 Ignition 1 (OEM pin 25)
	Gpio::C2, // PC2 Ignition 2 (OEM pin 26)
	Gpio::C3, // PC3 Ignition 3
	Gpio::C4, // PC4 Ignition 4
// "PB10 Injector 1 (OEM pin 35)",
// "PB11 Injector 2 (OEM pin 32)",
// "PB15 Injector 3 (OEM pin 33)",
// "PB12 Injector 4 (OEM pin 18)",
// "PB0 Idle Solenoid IAC (OEM pin 34)",
// "PB1 Aux PWM (OEM pin 27)",
// "PB3 EVAP Purge (OEM pin 7)",
// "PA15 Overboost Valve OBV (OEM pin 16)",
// "PB5 MIL Warning Lamp (OEM pin 12)",
// "PC13 Fuel Pump Relay (OEM pin 28)",
// "PC1 Ignition 1 (OEM pin 25)",
// "PC2 Ignition 2 (OEM pin 26)",
// "PC3 Ignition 3",
// "PC4 Ignition 4",
}
