// DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/RP-f405-board/connectors/rp_f405_connector.yaml
#pragma once

#define PIN_37 EFI_ADC_0
#define PIN_38 EFI_ADC_1
#define PIN_39 EFI_ADC_2
#define PIN_40 EFI_ADC_3
#define PIN_41 EFI_ADC_4
#define PIN_42 EFI_ADC_5
#define PIN_43 EFI_ADC_6
#define PIN_44 EFI_ADC_7
#define PIN_45 EFI_ADC_10
#define PIN_4 C6
#define PIN_23 C7
#define PIN_vss B13
#define PIN_21 B2
#define PIN_8 B4
#define PIN_14 B14
#define PIN_13 C5
#define PIN_25 C1
#define PIN_26 C2
#define PIN_ign3 C3
#define PIN_ign4 C4
#define PIN_35 B10
#define PIN_32 B11
#define PIN_33 B15
#define PIN_18 B12
#define PIN_34 B0
#define PIN_27 B1
#define PIN_7 B3
#define PIN_16 A15
#define PIN_12 B5
#define PIN_28 C13
